import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Un seul chapitre pour l'instant. Les autres seront ajoutés quand ils existeront :
// afficher des sections vides donne l'impression d'un site abandonné.
const sidebars: SidebarsConfig = {
  chapitreManipulation: [
    {
      type: 'autogenerated',
      dirName: 'manipulation',
    },
  ],
};

export default sidebars;
